# Generated by Django 5.0.1 on 2025-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_publicacion_visible_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
